### ISSUE TITLE
🔍 블록 에디터 검증

### ISSUE THREAD

**Issue by custardcream98** [ganada-labs/nlog-FE#1]
## 설명

nlog에 사용할 오픈소스 블록 에디터의 사용성을 검증합니다.

### 중점 비교 사항

* 안정성
  * 리액트와 함께 사용했을 때 동작이 보장되는지 여부를 중점으로 확인
* 확장성
  * 직접 커스텀 컴포넌트를 추가할 수 있는가? 그렇다면 자유도는? (추후 추가 기능이 생길것을 고려해 최대한 신중하게 파고들 예정)
* 디자인 (혹은 디자인 수정의 용이성)
* 커뮤니티 규모

### 비교 대상 (추후 추가될 수 있음)

* [Editor.js](https://editorjs.io/)
* [BlockNote](https://www.blocknotejs.org/)
* [Novel.sh](https://github.com/steven-tey/novel)
* [SmartBlock](https://appleple.github.io/smartblock/)
* [Yopta-Editor](https://github.com/Darginec05/Yopta-Editor)

* 혹은 간단한 Rich Text Editor 기반으로 직접 만들수 있을까? 가능성 확인 필요
  * [slate](https://github.com/ianstormtaylor/slate)

**Comment by dev2820** [comment]
Rich Text Editor를 직접 만드는 기반 기술은 `contenteditable` 입니다. 
https://medium.com/swlh/how-to-build-a-text-editor-like-notion-c510aedfdfcc

블록의 종류가 다양하고 markdown 문법을 같이 지원하기 위해 이런 저런 작업이 많이 필요하기 때문에 비용이 비싼편입니다. 따라서 직접 개발은 비추하는편. 우선 있는걸 사용하고 나중에 커스텀에 한계를 보면 그때 교체를 논하는 것을 추천합니다

**Comment by dev2820** [comment]
그리고 Editor.js는 제가 작년 겨울에 써봤는데 너무 구려서 힘들었습니다. 지금은 어떤지 모르겠는데 drag & drop을 지원 안해요. 다만 블럭 커스텀은 쉬운편입니다. 근데 진짜 너무 구렸음...

**Comment by dev2820** [comment]
저는 다음 사항들도 검증에 고려했으면 좋겠어요
- drag & drop 지원
- 커스텀 메뉴 추가 가능
- block을 json 형태로 input & output 할 수 있는지 여부

**Comment by custardcream98** [comment]
일정이 밀리고 있습니다ㅠㅠ 7일 => 10로 연장

**Comment by dev2820** [comment]
> 일정이 밀리고 있습니다ㅠㅠ 7일 => 10로 연장

@custardcream98 
이 테스크가 얼만큼 진행됐는지 알려줄 수 있나요? 너무 커진다면 완성한부분까지 마무리 짓고 새 테스크를 여는게 좋을 것 같아요

**Comment by custardcream98** [comment]
> > 일정이 밀리고 있습니다ㅠㅠ 7일 => 10로 연장
> 
> @custardcream98 
> 이 테스크가 얼만큼 진행됐는지 알려줄 수 있나요? 너무 커진다면 완성한부분까지 마무리 짓고 새 테스크를 여는게 좋을 것 같아요

아닙니다ㅠㅜ 너무 커서가 아니라 제가 더뎌서...

**Comment by custardcream98** [comment]
[검증 내용](https://www.notion.so/9fd51e72c9a74d7db37f6ea017329dc7?pvs=4)
