### ISSUE TITLE
🚀 개발 환경 설정

### ISSUE THREAD

**Issue by custardcream98** [ganada-labs/nlog-FE#3]
## 기능 설명

* 정해진 스택을 바탕으로 개발 환경을 구축합니다.
* 모노레포 설정으로 인해 시간이 많이 소요될것으로 보입니다.

## 참조

#2

**Comment by dev2820** [comment]
@custardcream98 

모노레포는 아직까진 부가적인 요소라 생각되는데, 시간이 오래 걸린다면 백로그로 남겨놓고 나중에 전환하는게 낫지 않을까요?

모노레포로 셋업하고 시작하는 것과 나중에 모노레포로 마이그레이션하는 것중 어느 것이 비용이 더 클까요?

**Comment by custardcream98** [comment]
네 지금으로선 모노레포로 할 이유가 없긴 하네요! 일단 하고 필요시 마이그레이션 하는게 좋겠습니당
